# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
repository: xstaticxgpx/gabe.tech
title: gabe.tech
email: root@gabe.tech
logo: /assets/img/logo.png
description: >- # this means to ignore newlines until "baseurl:"
    Experience from operational boots on the ground to high-level R&D.<br />
    Overall linux, scripting, devops guru.<br />
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gabe.tech" # the base hostname & protocol for your site, e.g. http://example.com
github_username: xstaticxgpx

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-paginate
  - jekyll-feed

# Exclude from processing.
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
